### ISSUE TITLE
Docs missing on npm

### ISSUE THREAD

**Issue by lukechilds** [sindresorhus/cycled#1]
The readme isn't published to npm: https://www.npmjs.com/package/cycled

You should probably publish a patch release to so people can read the docs directly on npm.

**Comment by gluons** [comment]
It's available now. Maybe npm registry delayed.

I've also faced this problem sometime. 😦

![screenshot-2018-3-28 cycled](https://user-images.githubusercontent.com/4688092/38034984-93f83a36-32cd-11e8-9482-6742018ce586.png)

**Comment by lukechilds** [comment]
Oh yeah, working for me now too 👍
