### ISSUE TITLE
Add Cycled#peek

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/cycled#11]
This could be useful to check values without actually switching to them:

```js
const Cycled = require('cycled');

const cycled = new Cycled([1, 2, 3]);

cycled.current();
//=> 1

cycled.peekNext();
//=> 2

cycled.peekNext();
//=> 2

cycled.peekPrevious();
//=> 3

cycled.next();
//=> 2

cycled.peek(1);
//=> 3
```

// @sindresorhus

**Comment by sindresorhus** [comment]
Yeah. Sounds useful, but I think it's enough with one method for this `.peak()`. You can just use 1 or -1 to go forward/backwards.
