### ISSUE TITLE
Infinite loop for Array spread or for-of loop

### ISSUE THREAD

**Issue by stefanjudis** [sindresorhus/cycled#5]
Hey Sindre,

I just came across this package and noticed that `cycled` object cause infinite loops when being used with Array spread and for-of loops which crashes browsers. Looking at the source code it looks like it's intended.

```
const cycled = new Cycled([1, 2, 3]);

const foo = [...cycled]; // infinite loop
for (let i of cycled) { ... } // infinite loop
```

Unfortunately, I can not wrap my head around at use case for this and I found it rather surprising because you're subclassing Array but this behavior differs from an Array. Can you give me a hint?

Thanks for the great work!

**Comment by ghost** [comment]
```js
* [Symbol.iterator]() {
		while (true) {
			yield this.next();
		}
}
```
*[Lonk](https://github.com/sindresorhus/cycled/blob/master/index.js#L13-L17)*

I don't really know too but it keeps up _index property updated without way to stop unless you `break` in loop

**Comment by sindresorhus** [comment]
Yes, the intention is that you can just break out of the loop when you had enough cycles. Now that this is an actual Array subclass, I agree it makes less sense by default and should be moved to a property.

So I propose we change it to run from the current index for the length of the array. That means if it's currently on index `3` with a length of 6, it will run to the end, start again, and run to index `2`.

We could name the property `indefinitely` and rename `reversed` to `indefinitelyReversed`.

Thoughts?

**Comment by kevva** [comment]
Sounds like a sensible option to me. Also, since it's an `Array` subclass now, do we even need a `reversed` property? Couldn't users just run `.reverse()` instead? It mutates the array though, so maybe not.

**Comment by sindresorhus** [comment]
I had the same thinking, but like you said, it mutates the array. Users might want to iterate backward while still having the array unchanged.
